spring:
  datasource:
    url: jdbc:h2:mem:assets-db
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: H2
    hibernate:
      ddl-auto: create
    show-sql: true
logging:
  level: debug